[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "历史文章"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "画廊"
  url = "gallery"
  weight = 3

[[main]]
  identifier = "posts"
  name = "发布"
  url = "posts"
  weight = 4